In [1]:
import numpy as np
import pandas as pd

# Q1   

In [2]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Q2 

In [3]:
my_array=np.zeros((10))
my_array[4]=1
my_array

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# Q3 

In [4]:
my_array=np.arange(0,9)
my_array=my_array.reshape((3,3))
my_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Q4 

In [5]:
np.random.random((3,3,3))

array([[[0.06127874, 0.94715258, 0.10304705],
        [0.63575044, 0.76091625, 0.34533595],
        [0.79791133, 0.8727064 , 0.94450268]],

       [[0.07949778, 0.32248737, 0.04647616],
        [0.62639407, 0.91118225, 0.2368841 ],
        [0.61686765, 0.11419956, 0.79964492]],

       [[0.56233732, 0.29918013, 0.44435237],
        [0.45328316, 0.73728283, 0.45908539],
        [0.87159918, 0.80652194, 0.99458384]]])

# Q5

In [6]:
a=np.ones((5,3))
b=np.ones((3,2))
print(a,'\n',b)
np.dot(a,b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

# Q6

In [7]:
a=np.arange(0,5)
b=np.zeros((5,5))
c=b+a
c

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

# Q7

In [8]:
print(c)
d=c.mean(axis=1)
print(d)
print(c-d)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[2. 2. 2. 2. 2.]
[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]


# Q8

In [9]:
print(c) #square matrix
c.diagonal()       

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


array([0., 1., 2., 3., 4.])

# Q9

In [10]:
a=np.array([0,1,2,3,2,2,2,])
np.bincount(a).argmax()

2

# Q10

In [11]:
a=np.random.random((10))
print(a)
a.sort()
print(a)

[0.66147968 0.59886369 0.16488583 0.93227368 0.39496574 0.2302703
 0.51020898 0.13740127 0.1344661  0.70881593]
[0.1344661  0.13740127 0.16488583 0.2302703  0.39496574 0.51020898
 0.59886369 0.66147968 0.70881593 0.93227368]


# Q11

In [12]:
chipo=pd.read_table('./chipotle.tsv')

# Q12

In [13]:
chipo.head(10)

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   
5         3         1                           Chicken Bowl   
6         3         1                          Side of Chips   
7         4         1                          Steak Burrito   
8         4         1                       Steak Soft Tacos   
9         5         1                          Steak Burrito   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98   
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98   
6                                                NaN     $1.69   
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75   
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25   
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

# Q13

In [14]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

# Q14

In [15]:
len(chipo.columns)

5

# Q15

In [16]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

# Q16

In [17]:
chipo.shape

(4622, 5)

# Q17,18

In [18]:
chipo.groupby('item_name')['quantity'].count()


item_name
6 Pack Soft Drink                         54
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            162
Bowl                                       2
Burrito                                    6
Canned Soda                              104
Canned Soft Drink                        301
Carnitas Bowl                             68
Carnitas Burrito                          59
Carnitas Crispy Tacos                      7
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             726
Chicken Burrito                          553
Chicken Crispy Tacos                      47
Chicken Salad                              9
Chicken Salad Bowl                       110


# Q19

In [19]:
chipo.groupby('choice_description')['quantity'].count()

choice_description
[Adobo-Marinated and Grilled Chicken, Pinto Beans, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]                                                                                 1
[Adobo-Marinated and Grilled Chicken, [Sour Cream, Cheese, Cilantro-Lime Rice]]                                                                                                                1
[Adobo-Marinated and Grilled Chicken]                                                                                                                                                          1
[Adobo-Marinated and Grilled Steak, [Sour Cream, Salsa, Cheese, Cilantro-Lime Rice, Guacamole]]                                                                                                1
[Adobo-Marinated and Grilled Steak]                                                                                                                                                            1
[Apple]         

# Q20

In [20]:
sum(chipo.groupby('order_id')['quantity'].count())

4622

# Q21

In [21]:
d=np.array(chipo['item_price'])
for i in range(0,len(d)):
    d[i]=d[i][1:]
print(d)
d=d.astype(float)

['2.39 ' '3.39 ' '3.39 ' ... '11.25 ' '8.75 ' '8.75 ']


In [22]:
chipo['item_price']=d

# Q22

In [23]:
chipo['item_price'].dtype

dtype('float64')

# Q23

In [24]:
sum(chipo['item_price'])

34500.16000000046

# Q24

In [25]:
chipo.groupby('item_name')['item_name'].count()

item_name
6 Pack Soft Drink                         54
Barbacoa Bowl                             66
Barbacoa Burrito                          91
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Barbacoa Soft Tacos                       25
Bottled Water                            162
Bowl                                       2
Burrito                                    6
Canned Soda                              104
Canned Soft Drink                        301
Carnitas Bowl                             68
Carnitas Burrito                          59
Carnitas Crispy Tacos                      7
Carnitas Salad                             1
Carnitas Salad Bowl                        6
Carnitas Soft Tacos                       40
Chicken Bowl                             726
Chicken Burrito                          553
Chicken Crispy Tacos                      47
Chicken Salad                              9
Chicken Salad Bowl                       110


In [26]:
x=chipo.groupby('item_name')['item_name'].count()
len(x)

50

# Q25

In [27]:
len(chipo.groupby('order_id')['quantity'].count())

1834

# Q26

In [28]:
chipo.groupby('order_id')['item_price'].sum()

order_id
1       11.56
2       16.98
3       12.67
4       21.00
5       13.70
6       17.50
7       15.70
8       10.88
9       10.67
10      13.20
11      12.38
12      14.37
13      10.88
14      10.08
15      10.88
16      10.68
17      10.08
18      24.90
19      13.90
20      36.20
21      23.36
22      12.98
23      11.17
24      12.07
25      11.38
26      20.50
27      13.90
28      33.70
29      17.98
30      23.36
        ...  
1805    20.00
1806    13.00
1807    18.64
1808    13.70
1809    14.45
1810    23.00
1811    29.25
1812    22.50
1813    17.50
1814    13.70
1815    12.50
1816    13.20
1817    13.00
1818    18.14
1819    13.20
1820    12.50
1821    13.70
1822    23.00
1823    12.15
1824    26.95
1825    66.50
1826    15.95
1827    32.95
1828    14.45
1829    24.25
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: item_price, Length: 1834, dtype: float64